version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    ports:
      - "8080:8080"
    #entrypoint: ["./wait-for-it.sh","db:5432", "--"]
    volumes:
      - .:/app
    command: gradle bootRun
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
